### PR TITLE
Update module paths to point to this fork

### PR DESCRIPTION
**Pull request by voltagex**
This changes the module paths in files to point to this specific fork of `dive`. This is mainly for neatness and the version code in #158 - which should make it clear that people are using a 'different' version of dive, which might become important in the future for bug reports

### CODE REVIEW

**Comment by jauderho** [comment]
Can you split this into two separate PRs? One for replacing the module paths and the other for version related changes.

It'lol make it easier to read through. Thanks.

**Comment by voltagex** [comment]
That sounds fine @jauderho, I'll try to get back to this soon.

**Comment by voltagex** [comment]
The version code has been removed from this branch. The could be squash-merged into main when you're ready :)

**Comment by jauderho** [comment]
I reviewed the PR and it was missing the search and replace in several spots. I just committed 4e07bbc4ae70dd02bf6d665b77401c588f5782f7 which should cover everything.

**Pull request closed without merging**
